fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        files: "^(?:backend|tests)/"
        exclude: "migrations"
        types: [python]
        entry: poetry
        args: ["run", "ruff", "check"]