# Generated by Django 5.1.4 on 2024-12-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Post',
        ),
    ]
